# Generated by Django 4.0.4 on 2022-05-15 22:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='photos/watches')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2022)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=30)),
                ('brand', models.CharField(choices=[('Cartier', 'Cartier'), ('Rolex', 'Rolex'), ('Patek Philippe', 'Patek Philippe'), ('Audemars Piguet', 'Audemars Piguet'), ('Omega', 'Omega')], max_length=30)),
                ('material', models.CharField(choices=[('Ceramic', 'Ceramic'), ('Titanium', 'Titanium'), ('Stainless steel', 'Stainless steel'), ('Steel watch', 'Steel watch')], max_length=30)),
                ('mechanism', models.CharField(choices=[('Mechanical', 'Mechanical'), ('Automatic', 'Automatic'), ('Quartz', 'Quartz'), ('Seiko Kinetic', 'Seiko Kinetic'), ('Solar', 'Solar')], max_length=30)),
                ('diameter', models.IntegerField(validators=[django.core.validators.MinValueValidator(24), django.core.validators.MaxValueValidator(56)])),
                ('glass', models.CharField(choices=[('Regular', 'Regular'), ('Plastic', 'Plastic'), ('Sapphire', 'Sapphire'), ('Crystal', 'Crystal'), ('Mineral', 'Mineral')], max_length=30)),
                ('waterResistantType', models.IntegerField(choices=[(30, '30 meters'), (50, '50 meters'), (100, '100 meters'), (200, '200 meters'), (300, '300 meters')])),
                ('description', models.TextField(blank=True, max_length=255)),
                ('availableItems', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewText', models.TextField(blank=True, max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.watch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
